### ISSUE TITLE
Breaking change in contain matcher

### ISSUE THREAD

**Issue by lochnesh** [vesln/robber.py#16]
After 9c86a01fba58faae5de8eec52ada8fbd01d8ee8c, I've noticed a breaking change in the contain matcher.  The following test examples work on cf7c9c1572611898190ca4a343e79b9e4283d369

```
>>> from robber import expect
>>> expect("test").to.contain("test")
<robber.expect.expect instance at 0x1105ae8c0>
>>> expect([{"test": "test"}]).to.contain({"test": "test"})
<robber.expect.expect instance at 0x1105ae680>
```

but do not work on 9c86a01fba58faae5de8eec52ada8fbd01d8ee8c

```
>>> from robber import expect
>>> expect("test").to.contain("test")
robber.bad_expectation.BadExpectation:
A = test
B = test
Expected A to contain B

>>> expect([{"test": "test"}]).to.contain({"test": "test"})
TypeError: unhashable type: 'dict'
```

Is there another matcher that could be used, or another approach taken to regain this functionality?

**Comment by catriuspham** [comment]
@lochnesh Sorry about this inconvenience, we're looking into this issue.

**Comment by catriuspham** [comment]
@lochnesh This issue will be fixed in https://github.com/EastAgile/robber.py/pull/66 and will be included in robber 1.1.3 right after the PR is merged, please wait for some days until it is up and live on pypi.

**Comment by catriuspham** [comment]
@lochnesh Thanks for your patience. The issue has been fixed. Now you can upgrade `robber` to 1.1.3 for a bug free experience. Please take a look and see if it satifies your need. Peace.

**Comment by lochnesh** [comment]
@catriuspham it works great!  Thank you!
